### ISSUE TITLE
Server returned non-200 status: 422 status code 422

### ISSUE THREAD

**Issue by olivierlacan** [gemnasium/toolbelt#46]
It would be useful if 422 status code responses displayed something about why the request is invalid. I'm guessing it's something to do with the arguments to `gemnasium projects create` being incorrect but it's basically impossible to debug otherwise.

**Comment by olivierlacan** [comment]
Pretty sure it turns out I hadn't run `gemnasium auth login` prior to this command, so this should be fairly simple to fix.

**Comment by olivierlacan** [comment]
@gravis I'm still getting this error with very little debug details available in the latest version. :-)

**Comment by gravis** [comment]
Sorry for the delay!
You should have a message (`auth: You must be logged in. Please use `gemnasium auth login` first, or pass your api token with --token or GEMNASIUM_TOKEN`) if not logged in already, instead of a 422.
Could you send more details to our support (https://support.gemnasium.com) so we can investigate?
Thanks

**Comment by gravis** [comment]
Ok I figured it out: Toolbelt will create "offline" projects, and it requires a paid plan for that.
We will fix that, thanks for reporting it.

**Comment by gravis** [comment]
@olivierlacan You can download a patched version here: https://github.com/gemnasium/toolbelt/releases/tag/0.2.10
(apt repo will be updated next week only)
Thanks for your patience
